server:
  port: 8080

spring:
  application:
    name: gateway

zuul:
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
  prefix: /api/v1
  sensitive-headers: Cookie, Set-Cookie
  routes:
    authentication:
      path: /users/**
      serviceId: authentication
      strip-prefix: false
    core:
      path: /test/**
      serviceId: core
      strip-prefix: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
