
server:
  port: 8010

spring:
  profiles: local
  application:
    name: authentication
  liquibase:
    change-log: classpath:db/changelog/dbchangelog.xml
    enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/english_portal_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


















